### ISSUE TITLE
Multiple CSS Selectors

### ISSUE THREAD

**Issue by cyouh95** [ArAt8787/prj-rev-bwfs-dasmoto#3]
Alternatively, you could use comma-separated selectors to specify shared properties among multiple elements:

```css
h1, h2, .price {
  font-family: Helvetica;
  font-weight: bold;
}
```

https://github.com/ArAt8787/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/style.css
